Repository TralaAI/Blazor, pull requests merged in 2025-06, with the labels that each got.

#4 Create dependabot.yml
  .github/dependabot.yml
Labels: enhancement

#3 Invent the backend service because I am sleep deprived
  Blazor.csproj
  Components/Pages/Aipredictions.razor
  Components/Pages/Home.razor
  Interfaces/IBackendService.cs
  Models/Enums/DTO/LitterType.cs
  Models/Enums/DTO/WeatherCondition.cs
  Models/Enums/LitterCategory.cs
  Models/Enums/WeatherCategory.cs
  Models/Litter.cs
  Models/LitterFilterDTO.cs
  Models/PredictionResponse.cs
  Program.cs
  Services/BackendService.cs
Labels: documentation

#5 Potential fix for code scanning alert no. 1: Workflow does not contain permissions
  .github/workflows/BlazorUI.yml
Labels: bug

#12 Enhance Frontend link to backend
  Components/Layout/NavMenu.razor
  Components/Pages/Aipredictions.razor
  Components/Pages/Heatmap.razor
  Components/Pages/History.razor
  Components/Pages/Settings.razor
  Interfaces/IHealthService.cs
  Interfaces/ILitterService.cs
  Models/Camera.cs
  Models/Health/HealthDetails.cs
  Models/Health/HealthStatus.cs
  Models/PredictionResponse.cs
  Program.cs
  Services/HealthService.cs
  Services/LitterService.cs
  wwwroot/app.css
Labels: enhancement

#13 Backend glazing
  Components/Layout/MainLayout.razor
  Components/Pages/Settings.razor
  Interfaces/IHealthService.cs
  Interfaces/ILitterService.cs
  Models/ModelStatusResponse.cs
  Services/HealthService.cs
  Services/LitterService.cs
  wwwroot/app.css
Labels: enhancement

#14 Backend data integration
  Components/Pages/Aipredictions.razor
Labels: enhancement

#16 History page
  Blazor.csproj
  Components/Pages/History.razor
  Interfaces/ILitterService.cs
  Models/Enums/LitterCategory.cs
  Models/Enums/WeatherCategory.cs
  Models/Litter.cs
  Services/LitterService.cs
  wwwroot/app.css
Labels: enhancement

#19 Heatmap data integration
  Components/App.razor
  Components/Pages/Aipredictions.razor
  Components/Pages/Heatmap.razor
  Models/Heatmap.cs
  wwwroot/app.css
  wwwroot/js/heatmapInterop.js
Labels: enhancement
